### ISSUE TITLE
Just a word of thanks

### ISSUE THREAD

**Issue by CSergienko** [react-workspaces/react-workspaces-playground#13]
Thank you for your work on @react-workspaces/react-scripts and this demo project - it really got me out of a nasty mess after I tried setting up my project using Yarn workspaces + Lerna + CRA and ran into issues with importing/exporting components across packages. I thought I was faced with going back to the drawing boards, but this works like a charm.

Two questions; what does long-term support look like for this fork, and is there any intention of getting it merged into CRA so workspaces are officially supported?

**Comment by F1LT3R** [comment]
There's no plan to support this long term yet. But I'm willing to do that while I'm using React for work. It's likely this will be measured in years rather than months.

If others want to step in an provide more support, that would be very welcome.

In terms of folding this back into CRA, I would very much like that. If there is support for this other than just myself, it may be easier to get in. My hope in starting this fork was to assess the amount of support to see if merging into CRA mainline was an effort worth undertaking.

**Comment by F1LT3R** [comment]
And thanks for the encouragement @CSergienko - I'm glad to hear the work has helped.
